name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step uses checkout action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
      # This step prints an output (time) from the previous step's action.
      - name: Hello checkout
        run: echo 'The time was ${{ steps.checkout.outputs.time }}.'
