name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nelarius/imnodes-docker-builder:latest
    steps:
      # This step uses checkout action: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
      # This step prints an output (time) from the previous step's action.
      - name: premake5
        run: premake5 gmake
